### ISSUE TITLE
Can't work out adding an image

### ISSUE THREAD

**Issue by untike** [FMatti/Minimal-CV#1]
First of all, that's a great CV, well done. But I can't seem to figure out how to add my own picture (.jpg) instead of the `\input{images/image.tex}` (l. 180)
Thanks in advance

**Comment by FMatti** [comment]
You may use `\includegraphics[scale=0.25]{images/image.jpg}` instead of `\scalebox{0.25}{\input{images/image.tex}}` after putting your `image.jpg` in the `images/` directory. Adjust the scale parameter such that the width of the image looks fine.
